### ISSUE TITLE
Rename to "Decoupling"?

### ISSUE THREAD

**Issue by tfpauly** [intarchboard/draft-obliviousness#2]
Another term instead of partitioning is Decoupling. The Principle of Decoupling, The Decoupling Principle, etc.

**Comment by fluffy** [comment]
I prefer the partitioning over decoupling

**Comment by mirjak** [comment]
if you look for privacy and data partitioning, you sooner or later will end up discussing k-anonymity where I believe this is the appropriate reference: https://dl.acm.org/doi/10.1142/S0218488502001648

**Comment by mirjak** [comment]
Also note that there is also privacy preserving data mining (PPDM) as a term of art (what is exactly what is used in PPM). Some example survey papers that might provide some overview (didn't read them yet fully):
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4643068/
https://www.ijert.org/research/techniques-for-privacy-preservation-in-data-mining-IJERTV4IS100473.pdf

**Comment by tfpauly** [comment]
Closing based on discussion.
