### ISSUE TITLE
Secondary contexts

### ISSUE THREAD

**Issue by martinthomson** [intarchboard/draft-obliviousness#33]
[Figure 4](https://intarchboard.github.io/draft-obliviousness/draft-kpw-iab-privacy-partitioning.html#figure-4) and [Figure 5](https://intarchboard.github.io/draft-obliviousness/draft-kpw-iab-privacy-partitioning.html#figure-5) shows a bunch of contexts in which the client does not participate.  Are those really helpful to include?

**Comment by tfpauly** [comment]
I think these are useful to include, personally, since they show the contexts across the entire flow. While client privacy is the goal, partitioning works in general. Happy to hear other opinions, though!

**Comment by chris-wood** [comment]
Yeah, I think we ought to include them. Maybe we should add text that actually references them though? For example, we might say that, in the two hop arrangement, Proxy B sees: context is shares with the Client (TLS session), context it shares with Proxy A (IP address and transport bits), and context it shares with the Target (transport and TLS session).

**Comment by tfpauly** [comment]
We do talk about them a bit, and my new text from #32 may help make it clearer by having a separate bullet?
